"""LensConfigBuilder fixture oracle scaffold.

Kibana's `@kbn/lens-embeddable-utils` / Lens-as-code builder is an authoritative
way to generate valid Lens attributes, but it lives in the Kibana TypeScript
toolchain. This module defines the *consumer-side* contract for those generated
fixtures so mig-to-kbn can enforce coverage and schema sanity without depending
on a Kibana checkout at test time.

Expected fixture JSON shape::

    {
      "name": "xy-line-basic",
      "chart_type": "xy",
      "series_type": "line",
      "data_source": "esql",
      "attributes": { ... Lens attributes generated by Kibana ... }
    }

The generator can be the external Docker/TS workflow; this oracle verifies that
the output is well-formed and covers the chart families our emitter claims to
support.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class LensFixture:
    name: str
    chart_type: str
    data_source: str
    attributes: dict[str, Any]
    series_type: str = ""

    @property
    def coverage_key(self) -> str:
        if self.chart_type == "xy" and self.series_type:
            return f"xy:{self.series_type}"
        return self.chart_type


def load_fixture(path: Path) -> LensFixture:
    payload = json.loads(Path(path).read_text())
    return LensFixture(
        name=str(payload.get("name") or Path(path).stem),
        chart_type=str(payload.get("chart_type") or ""),
        series_type=str(payload.get("series_type") or ""),
        data_source=str(payload.get("data_source") or ""),
        attributes=payload.get("attributes") if isinstance(payload.get("attributes"), dict) else {},
    )


def load_fixtures(path: Path) -> list[LensFixture]:
    return [load_fixture(p) for p in sorted(Path(path).glob("*.json"))]


def validate_fixture(fixture: LensFixture) -> list[str]:
    errors: list[str] = []
    if not fixture.name:
        errors.append("missing name")
    if not fixture.chart_type:
        errors.append("missing chart_type")
    if fixture.data_source not in {"esql", "data_view"}:
        errors.append(f"unsupported data_source {fixture.data_source!r}")
    if not fixture.attributes:
        errors.append("missing attributes")
    state = fixture.attributes.get("state") if isinstance(fixture.attributes, dict) else {}
    if not isinstance(state, dict):
        errors.append("attributes.state must be an object")
    return errors


def coverage_report(fixtures: list[LensFixture], required: set[str]) -> dict[str, Any]:
    available = {fixture.coverage_key for fixture in fixtures}
    return {
        "available": sorted(available),
        "required": sorted(required),
        "missing": sorted(required - available),
        "ok": not (required - available),
    }


def validate_fixture_dir(path: Path, required: set[str]) -> dict[str, Any]:
    fixtures = load_fixtures(path)
    errors: dict[str, list[str]] = {}
    for fixture in fixtures:
        fixture_errors = validate_fixture(fixture)
        if fixture_errors:
            errors[fixture.name] = fixture_errors
    coverage = coverage_report(fixtures, required)
    return {
        "fixtures": len(fixtures),
        "errors": errors,
        "coverage": coverage,
        "ok": not errors and coverage["ok"],
    }


def _build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="verifier.lens_fixtures",
        description="Validate LensConfigBuilder-generated fixture contract and coverage.",
    )
    parser.add_argument("--fixture-dir", type=Path, required=True)
    parser.add_argument("--require", action="append", default=[])
    parser.add_argument("--output", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_argparser().parse_args(argv)
    result = validate_fixture_dir(args.fixture_dir, set(args.require))
    if args.output:
        args.output.write_text(json.dumps(result, indent=2))
    print(json.dumps(result, indent=2))
    return 0 if result["ok"] else 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())

