"""LensConfigBuilder fixture oracle scaffold.

Kibana's `@kbn/lens-embeddable-utils` / Lens-as-code builder is an authoritative
way to generate valid Lens attributes, but it lives in the Kibana TypeScript
toolchain. This module defines the *consumer-side* contract for those generated
fixtures so mig-to-kbn can enforce coverage and schema sanity without depending
on a Kibana checkout at test time.

Preferred wrapper fixture JSON shape::

    {
      "name": "xy-line-basic",
      "chart_type": "xy",
      "series_type": "line",
      "data_source": "esql",
      "attributes": { ... Lens attributes generated by Kibana ... }
    }

The generator can be the external Docker/TS workflow; this oracle verifies that
the output is well-formed and covers the chart families our emitter claims to
support.

The public fixture generator also writes raw Lens attributes directly. Those are
accepted too: ``visualizationType`` and ``state.datasourceStates`` are used to
infer chart type and data-source kind.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class LensFixture:
    name: str
    chart_type: str
    data_source: str
    attributes: dict[str, Any]
    series_type: str = ""
    source_format: str = "wrapper"

    @property
    def coverage_key(self) -> str:
        if self.chart_type == "xy" and self.series_type:
            return f"xy:{self.series_type}"
        return self.chart_type


_VIS_TYPE_TO_CHART = {
    "lnsMetric": "metric",
    "lnsXY": "xy",
    "lnsPie": "pie",
    "lnsDatatable": "table",
    "lnsGauge": "gauge",
    "lnsHeatmap": "heatmap",
    "lnsTagcloud": "tagcloud",
    "lnsTreemap": "treemap",
    "lnsMosaic": "mosaic",
    "lnsWaffle": "waffle",
}


def _infer_chart_type(attributes: dict[str, Any], filename: str) -> str:
    explicit = _VIS_TYPE_TO_CHART.get(str(attributes.get("visualizationType") or ""))
    if explicit:
        return explicit
    stem = Path(filename).stem.lower()
    if stem.startswith("xy-") or stem.startswith("xy_"):
        return "xy"
    for name in ("metric", "gauge", "heatmap", "tagcloud", "treemap", "mosaic", "waffle", "pie", "datatable"):
        if stem.startswith(name):
            return "table" if name == "datatable" else name
    return ""


def _infer_data_source(attributes: dict[str, Any], filename: str) -> str:
    state = attributes.get("state") if isinstance(attributes.get("state"), dict) else {}
    ds = state.get("datasourceStates") if isinstance(state.get("datasourceStates"), dict) else {}
    if "textBased" in ds:
        return "esql"
    if "formBased" in ds:
        return "data_view"
    stem = Path(filename).stem.lower()
    if stem.endswith("-esql"):
        return "esql"
    if stem.endswith("-dataview"):
        return "data_view"
    return ""


def _infer_series_type(attributes: dict[str, Any], filename: str) -> str:
    state = attributes.get("state") if isinstance(attributes.get("state"), dict) else {}
    visualization = state.get("visualization") if isinstance(state.get("visualization"), dict) else {}
    if isinstance(visualization.get("preferredSeriesType"), str):
        return visualization["preferredSeriesType"]
    layers = visualization.get("layers")
    if isinstance(layers, list) and layers:
        first = layers[0] if isinstance(layers[0], dict) else {}
        if isinstance(first.get("seriesType"), str):
            return first["seriesType"]
    stem = Path(filename).stem.lower()
    for series in ("line", "area", "bar"):
        if series in stem:
            return series
    return ""


def _raw_attributes_fixture(payload: dict[str, Any], path: Path) -> LensFixture:
    return LensFixture(
        name=path.stem,
        chart_type=_infer_chart_type(payload, path.name),
        series_type=_infer_series_type(payload, path.name),
        data_source=_infer_data_source(payload, path.name),
        attributes=payload,
        source_format="raw_attributes",
    )


def load_fixture(path: Path) -> LensFixture:
    payload = json.loads(Path(path).read_text())
    if not isinstance(payload, dict):
        return LensFixture(name=Path(path).stem, chart_type="", data_source="", attributes={})
    if "attributes" not in payload and ("visualizationType" in payload or "state" in payload):
        return _raw_attributes_fixture(payload, Path(path))
    return LensFixture(
        name=str(payload.get("name") or Path(path).stem),
        chart_type=str(payload.get("chart_type") or ""),
        series_type=str(payload.get("series_type") or ""),
        data_source=str(payload.get("data_source") or ""),
        attributes=payload.get("attributes") if isinstance(payload.get("attributes"), dict) else {},
        source_format="wrapper",
    )


def load_fixtures(path: Path) -> list[LensFixture]:
    return [load_fixture(p) for p in sorted(Path(path).glob("*.json"))]


def validate_fixture(fixture: LensFixture) -> list[str]:
    errors: list[str] = []
    if not fixture.name:
        errors.append("missing name")
    if not fixture.chart_type:
        errors.append("missing chart_type")
    if fixture.data_source not in {"esql", "data_view"}:
        errors.append(f"unsupported data_source {fixture.data_source!r}")
    if not fixture.attributes:
        errors.append("missing attributes")
    state = fixture.attributes.get("state") if isinstance(fixture.attributes, dict) else {}
    if not isinstance(state, dict):
        errors.append("attributes.state must be an object")
    return errors


def coverage_report(fixtures: list[LensFixture], required: set[str]) -> dict[str, Any]:
    available = {fixture.coverage_key for fixture in fixtures}
    return {
        "available": sorted(available),
        "required": sorted(required),
        "missing": sorted(required - available),
        "ok": not (required - available),
    }


def validate_fixture_dir(path: Path, required: set[str]) -> dict[str, Any]:
    fixtures = load_fixtures(path)
    errors: dict[str, list[str]] = {}
    for fixture in fixtures:
        fixture_errors = validate_fixture(fixture)
        if fixture_errors:
            errors[fixture.name] = fixture_errors
    coverage = coverage_report(fixtures, required)
    return {
        "fixtures": len(fixtures),
        "errors": errors,
        "coverage": coverage,
        "by_source_format": _count_by(fixtures, lambda item: item.source_format),
        "by_data_source": _count_by(fixtures, lambda item: item.data_source),
        "ok": not errors and coverage["ok"],
    }


def _count_by(fixtures: list[LensFixture], key_fn) -> dict[str, int]:
    counts: dict[str, int] = {}
    for fixture in fixtures:
        key = str(key_fn(fixture) or "")
        counts[key] = counts.get(key, 0) + 1
    return counts


def _build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="verifier.lens_fixtures",
        description="Validate LensConfigBuilder-generated fixture contract and coverage.",
    )
    parser.add_argument("--fixture-dir", type=Path, required=True)
    parser.add_argument("--require", action="append", default=[])
    parser.add_argument("--output", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_argparser().parse_args(argv)
    result = validate_fixture_dir(args.fixture_dir, set(args.require))
    if args.output:
        args.output.write_text(json.dumps(result, indent=2))
    print(json.dumps(result, indent=2))
    return 0 if result["ok"] else 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())

