# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one or more contributor license agreements.
# SPDX-License-Identifier: Elastic-2.0

"""Offline Kibana-schema gate.

Validates every emitted dashboard YAML against the vendored Kibana
``DashboardConfig`` JSON Schema (``docs/dashboards/schema.json``) using
``jsonschema`` — no cluster, no external ``kb-dashboard-cli``. This is a fast,
deterministic pre-filter for "is the panel well-formed by Kibana's own
definition?" on every PR.

Important caveat (see the confidence-pyramid spec): the vendored schema is
generated by the *abandoned* ``kb-dashboard-core`` and can go stale, and the
YAML->JSON compiler has its own bugs — so passing this gate is necessary but not
sufficient. Real Kibana (the live render-audit / native Dashboards API) remains
the authority. This gate exists to catch the easy structural breakage cheaply.
"""

from __future__ import annotations

import glob
import json
from pathlib import Path

import jsonschema
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "docs" / "dashboards" / "schema.json"


def _validator() -> jsonschema.Draft202012Validator:
    schema = json.loads(SCHEMA_PATH.read_text())
    return jsonschema.Draft202012Validator(schema)


def test_vendored_schema_is_present_and_is_dashboard_config():
    assert SCHEMA_PATH.exists(), f"vendored Kibana schema missing at {SCHEMA_PATH}"
    schema = json.loads(SCHEMA_PATH.read_text())
    assert schema.get("title") == "DashboardConfig"
    assert "dashboards" in schema.get("required", [])


def test_emitted_corpus_yaml_validates_against_kibana_schema(grafana_corpus_dir):
    validator = _validator()
    yaml_files = sorted(glob.glob(str(grafana_corpus_dir / "yaml" / "*.yaml")))
    assert yaml_files, f"no emitted YAML under {grafana_corpus_dir}/yaml"

    failures: list[str] = []
    for path in yaml_files:
        doc = yaml.safe_load(Path(path).read_text())
        errors = sorted(validator.iter_errors(doc), key=lambda e: list(e.path))
        for err in errors:
            location = "/".join(str(p) for p in err.path) or "<root>"
            failures.append(f"{Path(path).name} @ {location}: {err.message}")

    assert not failures, (
        f"{len(failures)} Kibana-schema validation error(s) in emitted YAML:\n  "
        + "\n  ".join(failures[:20])
    )
