# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one or more contributor license agreements.
# SPDX-License-Identifier: Elastic-2.0

"""Offline Kibana-schema gate.

Validates every migrated dashboard against the vendored Kibana
``DashboardConfig`` JSON Schema (``docs/dashboards/schema.json``) using
``jsonschema`` — no cluster, no external ``kb-dashboard-cli``. This is a fast,
deterministic pre-filter for "is the panel well-formed by Kibana's own
definition?" on every PR.

The document under test is rebuilt from each run's ``ir/*.ir.json`` artifact
(``DashboardIR.to_yaml_dict``), which is exactly what the migration derives its
artifacts from; no dashboard YAML is written to disk any more.

Important caveat (see the confidence-pyramid spec): the vendored schema is
generated by the *abandoned* ``kb-dashboard-core`` and can go stale, and the
YAML->JSON compiler has its own bugs — so passing this gate is necessary but not
sufficient. Real Kibana (the live render-audit / native Dashboards API) remains
the authority. This gate exists to catch the easy structural breakage cheaply.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import jsonschema

from observability_migration.core.assets.dashboard import DashboardIR

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "docs" / "dashboards" / "schema.json"


def _validator() -> jsonschema.Draft202012Validator:
    schema = json.loads(SCHEMA_PATH.read_text())
    return jsonschema.Draft202012Validator(schema)


def test_vendored_schema_is_present_and_is_dashboard_config():
    assert SCHEMA_PATH.exists(), f"vendored Kibana schema missing at {SCHEMA_PATH}"
    schema = json.loads(SCHEMA_PATH.read_text())
    assert schema.get("title") == "DashboardConfig"
    assert "dashboards" in schema.get("required", [])


def _strip_panel_time_range_overrides(entry: dict[str, Any]) -> None:
    """Remove a panel-level ``esql.time_range`` before schema validation, in place.

    Recurses into ``section`` blocks. The Dashboards API accepts a panel
    ``config.time_range`` override (Grafana ``timeFrom``, see
    ``dashboards_api.py::map_yaml_panel``), but the vendored (abandoned)
    kb-dashboard-core schema predates that field: every ``ESQL*PanelConfig``
    definition declares ``additionalProperties: false`` with no ``time_range``
    property at all. Same category of known gap as the dashboard-level
    ``time_range``/``refresh_interval`` exclusion in ``DashboardIR.to_yaml_dict``
    -- a real Dashboards API capability the abandoned schema never modeled --
    so it is stripped here rather than either dropping the feature or letting
    a known-stale schema fail every corpus dashboard that uses it.
    """
    section = entry.get("section")
    if isinstance(section, dict):
        for sub in section.get("panels") or []:
            if isinstance(sub, dict):
                _strip_panel_time_range_overrides(sub)
        return
    esql = entry.get("esql")
    if isinstance(esql, dict):
        esql.pop("time_range", None)


def _schema_failures(dashboards_dir: Path) -> list[str]:
    """Validate every migrated dashboard under ``dashboards_dir`` against the
    vendored Kibana schema; return human-readable failure strings (empty == ok)."""
    validator = _validator()
    ir_files = sorted((dashboards_dir / "ir").glob("*.ir.json"))
    assert ir_files, f"no migrated IR artifacts under {dashboards_dir}/ir"

    failures: list[str] = []
    for path in ir_files:
        artifact = json.loads(path.read_text())
        dashboard_ir = DashboardIR.from_dict(artifact["dashboard_ir"])
        doc = {"dashboards": [dashboard_ir.to_yaml_dict()]}
        for dashboard in doc["dashboards"]:
            for entry in dashboard.get("panels") or []:
                if isinstance(entry, dict):
                    _strip_panel_time_range_overrides(entry)
        errors = sorted(validator.iter_errors(doc), key=lambda e: list(e.path))
        for err in errors:
            location = "/".join(str(p) for p in err.path) or "<root>"
            failures.append(f"{path.name} @ {location}: {err.message}")
    return failures


def test_emitted_corpus_yaml_validates_against_kibana_schema(grafana_corpus_dir):
    failures = _schema_failures(grafana_corpus_dir)
    assert not failures, (
        f"{len(failures)} Kibana-schema validation error(s) in migrated Grafana dashboards:\n  "
        + "\n  ".join(failures[:20])
    )


def test_emitted_datadog_corpus_yaml_validates_against_kibana_schema(datadog_corpus_dir):
    failures = _schema_failures(datadog_corpus_dir)
    assert not failures, (
        f"{len(failures)} Kibana-schema validation error(s) in migrated Datadog dashboards:\n  "
        + "\n  ".join(failures[:20])
    )
